# Generated by Django 5.0.2 on 2025-06-02 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('quantity_liters', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(20000)])),
                ('delivery_address', models.TextField()),
                ('delivery_date', models.DateField()),
                ('delivery_time_preference', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('assigned', 'Asignado'), ('in_transit', 'En Camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('special_instructions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_confirmation_code', models.CharField(blank=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('delivery_time_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('water_quality_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('operator_service_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('assigned', 'Asignado'), ('in_transit', 'En Camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('assigned', 'Asignado'), ('in_transit', 'En Camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
