# Generated by Django 5.0.2 on 2025-07-11 07:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio total del pedido en MXN', max_digits=10),
        ),
    ]
