# Generated by Django 5.0.2 on 2025-07-15 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_price'),
        ('unidades', '0002_unidad_assigned_operator_unidad_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='order',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='unidades.unidad', verbose_name='Unidad asignada'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('assigned', 'Asignado'), ('in_transit', 'En camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('assigned', 'Asignado'), ('in_transit', 'En camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('assigned', 'Asignado'), ('in_transit', 'En camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], max_length=20),
        ),
    ]
