# Generated by Django 5.0.2 on 2025-07-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_unidad_fk_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('AO', 'Álvaro Obregón'), ('AZ', 'Azcapotzalco'), ('BJ', 'Benito Juárez'), ('CO', 'Coyoacán'), ('CU', 'Cuauhtémoc'), ('CJ', 'Cuajimalpa de Morelos'), ('GA', 'Gustavo A. Madero'), ('IZ', 'Iztacalco'), ('IH', 'Iztapalapa'), ('MC', 'Magdalena Contreras'), ('MI', 'Miguel Hidalgo'), ('MA', 'Milpa Alta'), ('TL', 'Tláhuac'), ('TM', 'Tlalpan'), ('VC', 'Venustiano Carranza'), ('XO', 'Xochimilco'), ('ACO', 'Acolman'), ('AME', 'Amecameca'), ('APA', 'Apaxco'), ('ATC', 'Atenco'), ('ATL', 'Atizapán de Zaragoza'), ('CAP', 'Capulhuac'), ('CHI', 'Chicoloapan'), ('CHT', 'Chimalhuacán'), ('CJC', 'Coacalco de Berriozábal'), ('CME', 'Cuautitlán México'), ('CIZ', 'Cuautitlán Izcalli'), ('ECT', 'Ecatepec de Morelos'), ('HIX', 'Huehuetoca'), ('HZN', 'Hueypoxtla'), ('IZC', 'Ixtapaluca'), ('JAL', 'Jaltenco'), ('LNE', 'La Paz'), ('LCO', 'Lerma'), ('MEL', 'Melchor Ocampo'), ('NZA', 'Nezahualcóyotl'), ('NIC', 'Nicolás Romero'), ('NUP', 'Nopaltepec'), ('OTU', 'Otumba'), ('PAP', 'Papalotla'), ('SLM', 'San Martín de las Pirámides'), ('SFE', 'San Felipe del Progreso'), ('SFS', 'San Francisco Soyaniquilpan'), ('SOX', 'Santo Tomás'), ('TEC', 'Tecámac'), ('TEM', 'Temamatla'), ('TEN', 'Tenango del Aire'), ('TEO', 'Teoloyucan'), ('TEX', 'Texcoco'), ('TLA', 'Tlalnepantla de Baz'), ('TLN', 'Tepotzotlán'), ('TNT', 'Teotihuacán'), ('TUL', 'Tultitlán'), ('VCS', 'Valle de Chalco Solidaridad'), ('ZMP', 'Zumpango')], max_length=4, unique=True)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precio por Zona',
                'verbose_name_plural': 'Precios por Zona',
                'ordering': ['zone'],
            },
        ),
    ]
