# Generated by Django 5.0.2 on 2025-07-30 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_fondocomision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionDescontada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('AO', 'Álvaro Obregón'), ('AZ', 'Azcapotzalco'), ('BJ', 'Benito Juárez'), ('CO', 'Coyoacán'), ('CU', 'Cuauhtémoc'), ('CJ', 'Cuajimalpa de Morelos'), ('GA', 'Gustavo A. Madero'), ('IZ', 'Iztacalco'), ('IH', 'Iztapalapa'), ('MC', 'Magdalena Contreras'), ('MI', 'Miguel Hidalgo'), ('MA', 'Milpa Alta'), ('TL', 'Tláhuac'), ('TM', 'Tlalpan'), ('VC', 'Venustiano Carranza'), ('XO', 'Xochimilco'), ('ACO', 'Acolman'), ('AME', 'Amecameca'), ('APA', 'Apaxco'), ('ATC', 'Atenco'), ('ATL', 'Atizapán de Zaragoza'), ('CAP', 'Capulhuac'), ('CHI', 'Chicoloapan'), ('CHT', 'Chimalhuacán'), ('CJC', 'Coacalco de Berriozábal'), ('CME', 'Cuautitlán México'), ('CIZ', 'Cuautitlán Izcalli'), ('ECT', 'Ecatepec de Morelos'), ('HIX', 'Huehuetoca'), ('HZN', 'Hueypoxtla'), ('IZC', 'Ixtapaluca'), ('JAL', 'Jaltenco'), ('LNE', 'La Paz'), ('LCO', 'Lerma'), ('MEL', 'Melchor Ocampo'), ('NZA', 'Nezahualcóyotl'), ('NIC', 'Nicolás Romero'), ('NUP', 'Nopaltepec'), ('OTU', 'Otumba'), ('PAP', 'Papalotla'), ('SLM', 'San Martín de las Pirámides'), ('SFE', 'San Felipe del Progreso'), ('SFS', 'San Francisco Soyaniquilpan'), ('SOX', 'Santo Tomás'), ('TEC', 'Tecámac'), ('TEM', 'Temamatla'), ('TEN', 'Tenango del Aire'), ('TEO', 'Teoloyucan'), ('TEX', 'Texcoco'), ('TLA', 'Tlalnepantla de Baz'), ('TLN', 'Tepotzotlán'), ('TNT', 'Teotihuacán'), ('TUL', 'Tultitlán'), ('VCS', 'Valle de Chalco Solidaridad'), ('ZMP', 'Zumpango')], max_length=4)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision', to='orders.order')),
            ],
            options={
                'verbose_name': 'Comisión descontada',
                'verbose_name_plural': 'Comisiones descontadas',
                'ordering': ['-fecha'],
            },
        ),
    ]
