# Generated by Django 5.0.2 on 2025-07-06 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderrating_delivery_time_rating_and_more'),
        ('pipa_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='thread',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='orders.order'),
        ),
    ]
