# Generated by Django 5.0.2 on 2025-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipa_messages', '0002_alter_message_options_alter_thread_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_seen_client',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='last_seen_operator',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
