# Generated by Django 5.0.2 on 2025-06-02 09:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=20, unique=True, verbose_name='ID de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('bank_transfer', 'Transferencia Bancaria'), ('oxxo', 'OXXO'), ('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito')], max_length=20, verbose_name='Método de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=15, verbose_name='Estado')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de Transacción')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='Número de Cuenta')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Comprobante de Pago')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Factura')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Razón de Fallo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Pedido')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Procesado Por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Factura')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('client_address', models.TextField(verbose_name='Dirección del Cliente')),
                ('client_tax_id', models.CharField(blank=True, max_length=20, verbose_name='RFC del Cliente')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuestos')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('issue_date', models.DateField(verbose_name='Fecha de Emisión')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='draft', max_length=15, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='Pedido')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Base')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Porcentaje de Comisión')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Comisión')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('calculated', 'Calculada'), ('paid', 'Pagada')], default='pending', max_length=15, verbose_name='Estado')),
                ('calculated_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cálculo')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('operator', models.ForeignKey(limit_choices_to={'user_type': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='orders.order', verbose_name='Pedido')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'method'], name='payments_pa_status_75d3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', 'status'], name='payments_pa_client__39a683_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['due_date'], name='payments_pa_due_dat_752274_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
    ]
