# Generated by Django 5.0.2 on 2025-07-05 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderrating_delivery_time_rating_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='order',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_status_75d3b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_client__39a683_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_due_dat_752274_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_payment_1d6e55_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_image',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.DeleteModel(
            name='Commission',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
