# Generated by Django 5.0.2 on 2025-07-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comprobante',
            field=models.ImageField(blank=True, help_text='Sube el comprobante si el pago fue por transferencia u OXXO.', null=True, upload_to='comprobantes_pagos/'),
        ),
    ]
