# Generated by Django 5.0.2 on 2025-06-02 02:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True, verbose_name='Placas')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)], verbose_name='Año')),
                ('vehicle_type', models.CharField(choices=[('small', 'Pequeña (≤ 5 000 L)'), ('medium', 'Mediana (5 000 – 10 000 L)'), ('large', 'Grande (10 000 – 20 000 L)'), ('extra_large', 'Extra Grande (> 20 000 L)')], max_length=15, verbose_name='Tipo de Vehículo')),
                ('capacity_liters', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(30000)], verbose_name='Capacidad (Litros)')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('maintenance', 'En Mantenimiento'), ('out_of_service', 'Fuera de Servicio'), ('retired', 'Retirado')], db_index=True, default='active', max_length=15, verbose_name='Estado')),
                ('engine_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número de Motor')),
                ('chassis_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número de Chasis')),
                ('registration_expiry', models.DateField(verbose_name='Vencimiento de Registro')),
                ('insurance_expiry', models.DateField(verbose_name='Vencimiento de Seguro')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Último Mantenimiento')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Próximo Mantenimiento')),
                ('current_location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación Actual')),
                ('odometer_reading', models.PositiveIntegerField(default=0, verbose_name='Kilometraje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('assigned_operator', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'operator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Operador Asignado')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['license_plate'],
                'indexes': [models.Index(fields=['status', 'vehicle_type'], name='vehicles_ve_status_6732a2_idx'), models.Index(fields=['assigned_operator'], name='vehicles_ve_assigne_94ed20_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('engine_number',), name='unique_engine_number'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('chassis_number',), name='unique_chassis_number'),
        ),
    ]
