# Generated by Django 5.0.2 on 2025-07-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('small', 'Pequeña (≤\u202f5\u202f000\u202fL)'), ('medium', 'Mediana (5\u202f000\u202f–\u202f10\u202f000\u202fL)'), ('large', 'Grande (10\u202f000\u202f–\u202f20\u202f000\u202fL)'), ('extra_large', 'Extra Grande (>\u202f20\u202f000\u202fL)')], max_length=15, verbose_name='Tipo de Vehículo'),
        ),
    ]
