# Generated by Django 5.0.2 on 2025-07-14 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='unique_engine_number',
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='unique_chassis_number',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_ve_status_6732a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_ve_assigne_94ed20_idx',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity_liters',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='chassis_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='engine_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_maintenance',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='next_maintenance',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='odometer_reading',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity_litres',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad (L)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Número de placas'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='assigned_operator',
            field=models.OneToOneField(limit_choices_to={'user_type': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
