# Generated by Django 5.0.2 on 2025-07-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_litres',
            field=models.PositiveIntegerField(verbose_name='Capacidad del tanque (L)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número de placas'),
        ),
    ]
