# Generated by Django 5.0.2 on 2025-06-02 17:05

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username',
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Calificación Promedio'),
        ),
    ]
