# Generated by Django 5.0.2 on 2025-06-18 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_remove_user_unique_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='total_liters',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de Litros'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='license_expiry',
            field=models.DateField(db_index=True, verbose_name='Vencimiento de Licencia'),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='license_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Licencia'),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='operatorprofile',
            index=models.Index(fields=['is_active'], name='users_opera_is_acti_7cbe1a_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorprofile',
            index=models.Index(fields=['license_expiry'], name='users_opera_license_5fbf55_idx'),
        ),
    ]
