# Generated by Django 5.0.2 on 2025-06-28 19:18

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clientprofile_updated_at_operatorprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=None, size=[512, 512], upload_to='profiles/', verbose_name='Foto de Perfil'),
        ),
    ]
